CI Workflow (#1)
* fix: golint exit status

* fix: lint issues are fixed, codecov action added

* fix: lint errors are fixed

* fix: build error

* fix: codecov yaml added

* fix: codecov yaml updated

* fix: ci yaml

* Update codecov.yml

* fix: ci yaml and codecov yaml updated

* fix: test coverage threshold added

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -49,11 +49,33 @@ jobs:
         with:
           version: latest
 
-      # - name: Install golint
-      #   run: go install golang.org/x/lint/golint@latest
+      - name: Install golint
+        run: go install golang.org/x/lint/golint@latest
 
-      # - name: Run golint
-      #   run: golint ./...
+      - name: Run golint
+        run: golint -set_exit_status ./...
 
       - name: Run tests
-        run: go test -race -vet=off ./...
+        run: go test -race -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic -vet=off ./...
+
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v3
+        with:
+          fail_ci_if_error: true
+          verbose: true
+
+      - name: Quality Gate - Test coverage shall be above threshold
+        env:
+          TESTCOVERAGE_THRESHOLD: 80
+        run: |
+            echo "Quality Gate: checking test coverage is above threshold ..."
+            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+            totalCoverage=`go tool cover -func=coverage.txt | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Current test coverage : $totalCoverage %"
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                echo "OK"
+            else
+                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                echo "Failed"
+                exit 1
+            fi
